// Code generated by protoc-gen-go. DO NOT EDIT.
// source: video/videopb/video.proto

package videopb

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Video struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Video) Reset()         { *m = Video{} }
func (m *Video) String() string { return proto.CompactTextString(m) }
func (*Video) ProtoMessage()    {}
func (*Video) Descriptor() ([]byte, []int) {
	return fileDescriptor_d39aa967dd2fa8d8, []int{0}
}

func (m *Video) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Video.Unmarshal(m, b)
}
func (m *Video) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Video.Marshal(b, m, deterministic)
}
func (m *Video) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Video.Merge(m, src)
}
func (m *Video) XXX_Size() int {
	return xxx_messageInfo_Video.Size(m)
}
func (m *Video) XXX_DiscardUnknown() {
	xxx_messageInfo_Video.DiscardUnknown(m)
}

var xxx_messageInfo_Video proto.InternalMessageInfo

func (m *Video) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type VideoStreamRequest struct {
	Video                *Video   `protobuf:"bytes,1,opt,name=video,proto3" json:"video,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VideoStreamRequest) Reset()         { *m = VideoStreamRequest{} }
func (m *VideoStreamRequest) String() string { return proto.CompactTextString(m) }
func (*VideoStreamRequest) ProtoMessage()    {}
func (*VideoStreamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d39aa967dd2fa8d8, []int{1}
}

func (m *VideoStreamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VideoStreamRequest.Unmarshal(m, b)
}
func (m *VideoStreamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VideoStreamRequest.Marshal(b, m, deterministic)
}
func (m *VideoStreamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VideoStreamRequest.Merge(m, src)
}
func (m *VideoStreamRequest) XXX_Size() int {
	return xxx_messageInfo_VideoStreamRequest.Size(m)
}
func (m *VideoStreamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VideoStreamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VideoStreamRequest proto.InternalMessageInfo

func (m *VideoStreamRequest) GetVideo() *Video {
	if m != nil {
		return m.Video
	}
	return nil
}

type VideoStreamResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VideoStreamResponse) Reset()         { *m = VideoStreamResponse{} }
func (m *VideoStreamResponse) String() string { return proto.CompactTextString(m) }
func (*VideoStreamResponse) ProtoMessage()    {}
func (*VideoStreamResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d39aa967dd2fa8d8, []int{2}
}

func (m *VideoStreamResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VideoStreamResponse.Unmarshal(m, b)
}
func (m *VideoStreamResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VideoStreamResponse.Marshal(b, m, deterministic)
}
func (m *VideoStreamResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VideoStreamResponse.Merge(m, src)
}
func (m *VideoStreamResponse) XXX_Size() int {
	return xxx_messageInfo_VideoStreamResponse.Size(m)
}
func (m *VideoStreamResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VideoStreamResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VideoStreamResponse proto.InternalMessageInfo

func (m *VideoStreamResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*Video)(nil), "video.Video")
	proto.RegisterType((*VideoStreamRequest)(nil), "video.VideoStreamRequest")
	proto.RegisterType((*VideoStreamResponse)(nil), "video.VideoStreamResponse")
}

func init() { proto.RegisterFile("video/videopb/video.proto", fileDescriptor_d39aa967dd2fa8d8) }

var fileDescriptor_d39aa967dd2fa8d8 = []byte{
	// 181 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2c, 0xcb, 0x4c, 0x49,
	0xcd, 0xd7, 0x07, 0x93, 0x05, 0x49, 0x10, 0x5a, 0xaf, 0xa0, 0x28, 0xbf, 0x24, 0x5f, 0x88, 0x15,
	0xcc, 0x51, 0x92, 0xe6, 0x62, 0x0d, 0x03, 0x31, 0x84, 0x84, 0xb8, 0x58, 0xf2, 0x12, 0x73, 0x53,
	0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x25, 0x0b, 0x2e, 0x21, 0xb0, 0x64, 0x70,
	0x49, 0x51, 0x6a, 0x62, 0x6e, 0x50, 0x6a, 0x61, 0x69, 0x6a, 0x71, 0x89, 0x90, 0x12, 0x17, 0x44,
	0x2f, 0x58, 0x29, 0xb7, 0x11, 0x8f, 0x1e, 0xc4, 0x58, 0xb0, 0xca, 0x20, 0xa8, 0xb1, 0xba, 0x5c,
	0xc2, 0x28, 0x3a, 0x8b, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x85, 0xc4, 0xb8, 0xd8, 0x8a, 0x52, 0x8b,
	0x4b, 0x73, 0x4a, 0xa0, 0xd6, 0x40, 0x79, 0x46, 0x51, 0x5c, 0x3c, 0x10, 0xe5, 0xa9, 0x45, 0x65,
	0x99, 0xc9, 0xa9, 0x42, 0x5e, 0x5c, 0xdc, 0x48, 0xda, 0x85, 0x24, 0x91, 0xad, 0x40, 0x71, 0x8c,
	0x94, 0x14, 0x36, 0x29, 0x88, 0x6d, 0x4a, 0x0c, 0x1a, 0x8c, 0x06, 0x8c, 0x4e, 0x9c, 0x51, 0xec,
	0x50, 0xff, 0x27, 0xb1, 0x81, 0xbd, 0x6e, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xca, 0xed, 0xbc,
	0x89, 0x17, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VideoServiceClient is the client API for VideoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VideoServiceClient interface {
	// Bidirectional
	VideoStream(ctx context.Context, opts ...grpc.CallOption) (VideoService_VideoStreamClient, error)
}

type videoServiceClient struct {
	cc *grpc.ClientConn
}

func NewVideoServiceClient(cc *grpc.ClientConn) VideoServiceClient {
	return &videoServiceClient{cc}
}

func (c *videoServiceClient) VideoStream(ctx context.Context, opts ...grpc.CallOption) (VideoService_VideoStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_VideoService_serviceDesc.Streams[0], "/video.VideoService/VideoStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &videoServiceVideoStreamClient{stream}
	return x, nil
}

type VideoService_VideoStreamClient interface {
	Send(*VideoStreamRequest) error
	Recv() (*VideoStreamResponse, error)
	grpc.ClientStream
}

type videoServiceVideoStreamClient struct {
	grpc.ClientStream
}

func (x *videoServiceVideoStreamClient) Send(m *VideoStreamRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *videoServiceVideoStreamClient) Recv() (*VideoStreamResponse, error) {
	m := new(VideoStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// VideoServiceServer is the server API for VideoService service.
type VideoServiceServer interface {
	// Bidirectional
	VideoStream(VideoService_VideoStreamServer) error
}

// UnimplementedVideoServiceServer can be embedded to have forward compatible implementations.
type UnimplementedVideoServiceServer struct {
}

func (*UnimplementedVideoServiceServer) VideoStream(srv VideoService_VideoStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method VideoStream not implemented")
}

func RegisterVideoServiceServer(s *grpc.Server, srv VideoServiceServer) {
	s.RegisterService(&_VideoService_serviceDesc, srv)
}

func _VideoService_VideoStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(VideoServiceServer).VideoStream(&videoServiceVideoStreamServer{stream})
}

type VideoService_VideoStreamServer interface {
	Send(*VideoStreamResponse) error
	Recv() (*VideoStreamRequest, error)
	grpc.ServerStream
}

type videoServiceVideoStreamServer struct {
	grpc.ServerStream
}

func (x *videoServiceVideoStreamServer) Send(m *VideoStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *videoServiceVideoStreamServer) Recv() (*VideoStreamRequest, error) {
	m := new(VideoStreamRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _VideoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "video.VideoService",
	HandlerType: (*VideoServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "VideoStream",
			Handler:       _VideoService_VideoStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "video/videopb/video.proto",
}
